#!/usr/bin/env node
const fs   = require('fs')
const path = require('path')
const os   = require('os')
const cp   = require('child_process')
const crypto = require('crypto')

const ROOT     = __dirname
const SRC_DIR  = path.join(ROOT, 'src')
const OUT_FILE = path.join(ROOT, 'index.html')

// Sanity floors — a truncated transfer drops below these. Adjust if the app
// legitimately shrinks a lot.
const MIN_JS_MODULES = 15
const MIN_OUTPUT_KB  = 140

// sha256 of a shipped file (repo root), used to write checksums.txt.
const fileHash = (f) => crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, f))).digest('hex')

// Called bare but provided by the browser / CDN libraries (not app code).
// Add a name here if the undefined-function scan reports a false positive.
const KNOWN_GLOBALS = new Set([
  'setTimeout','setInterval','clearTimeout','clearInterval','requestAnimationFrame',
  'getComputedStyle','encodeURIComponent','decodeURIComponent','structuredClone',
  'queueMicrotask','parseInt','parseFloat','isNaN','fetch','confirm','alert','prompt','atob','btoa',
  'marked','DOMPurify','Tesseract','pdfjsLib','mammoth','XLSX',
  'onData'  // callback parameter of streamSse() (12-transport), not a global fn
])
const KEYWORDS = new Set('if for while switch catch return typeof function await throw delete void do else new in of yield case try finally with class extends super'.split(' '))

const TOP_BANNER = '<!-- Generated by build.js from src/ — do not edit index.html directly -->\n'
const sectionBanner = (f) => '\n// SECTION: ' + f + '\n'
const readSrc = (name) => fs.readFileSync(path.join(SRC_DIR, name), 'utf8')

function nodeCheck(code) {
  const tmp = path.join(os.tmpdir(), '_lcl_chk_' + Math.random().toString(36).slice(2) + '.js')
  fs.writeFileSync(tmp, code, 'utf8')
  const r = cp.spawnSync(process.execPath, ['--check', tmp], { encoding: 'utf8' })
  try { fs.unlinkSync(tmp) } catch (e) {}
  return r.status === 0 ? null : (r.stderr || r.stdout || 'syntax error').trim()
}

// Largest inline <script> block = the app bundle (ignores CDN <script src> tags).
function appBundle(out) {
  const noCdn = out.replace(/<script src="[^"]*"><\/script>/g, '')
  const blocks = [...noCdn.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m => m[1])
  return blocks.length ? blocks.reduce((a, b) => b.length > a.length ? b : a) : null
}

// Strip block comments and full-line // comments so the scan never trips on
// example calls written in comments (e.g. "see cancel: 'foo()'"). Full-line
// only, so URLs like https:// inside string literals are left untouched.
function stripComments(s) {
  return s.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/^[ \t]*\/\/.*$/gm, '')
}

function undefinedFns(bundleJs, headHtml) {
  bundleJs = stripComments(bundleJs); headHtml = stripComments(headHtml)
  const defined = new Set(); let m
  const r1 = /\bfunction\s+(\w+)/g;            while ((m = r1.exec(bundleJs))) defined.add(m[1])
  const r2 = /\b(?:const|let|var)\s+(\w+)\s*=/g; while ((m = r2.exec(bundleJs))) defined.add(m[1])
  const calls = new Set()
  const rc = /(?<![.\w])([a-zA-Z_]\w*)\s*\(/g; while ((m = rc.exec(bundleJs))) calls.add(m[1])
  const ro = /on\w+="(\w+)\(/g;                while ((m = ro.exec(headHtml))) calls.add(m[1])
  const out = []
  for (const c of calls) {
    if (defined.has(c) || KNOWN_GLOBALS.has(c) || KEYWORDS.has(c)) continue
    // app fns are lowercase-initial camelCase (buildContent, renderChips). This
    // skips constructors (AbortController) and prose/CSS words (rgba, resolve).
    if (!/^[a-z]/.test(c) || !/[a-z][A-Z]/.test(c)) continue
    out.push(c)
  }
  return out.sort()
}

const pad = (s) => (s + ' ').padEnd(40, '.')

function verify(out, jsFiles) {
  console.log('\nRunning checks:')
  const errors = []
  const T = 5

  console.log('  [1/' + T + '] ' + pad('Null-byte scan') + (out.indexOf('\x00') === -1 ? ' PASS' : ' FAIL'))
  if (out.indexOf('\x00') !== -1) errors.push('null bytes in output (corrupt source?)')

  const miss = jsFiles.filter(f => out.indexOf('SECTION: ' + f) === -1)
  const kb = out.length / 1024
  const sizeOk = jsFiles.length >= MIN_JS_MODULES && kb >= MIN_OUTPUT_KB
  console.log('  [2/' + T + '] ' + pad('Banners + size (' + jsFiles.length + ' mods, ' + kb.toFixed(0) + ' KB)') + (!miss.length && sizeOk ? ' PASS' : ' FAIL'))
  miss.forEach(f => errors.push('missing section banner: ' + f))
  if (jsFiles.length < MIN_JS_MODULES) errors.push('only ' + jsFiles.length + ' JS modules (< ' + MIN_JS_MODULES + ') — source likely truncated')
  if (kb < MIN_OUTPUT_KB) errors.push('output ' + kb.toFixed(0) + ' KB (< ' + MIN_OUTPUT_KB + ' KB) — source likely truncated')

  const badMods = []
  for (const f of jsFiles) { const e = nodeCheck(readSrc(f)); if (e) badMods.push(f + ' — ' + e.split('\n')[0]) }
  console.log('  [3/' + T + '] ' + pad('Per-module syntax (' + jsFiles.length + ')') + (!badMods.length ? ' PASS' : ' FAIL'))
  badMods.forEach(e => errors.push('module syntax: ' + e))

  const bundle = appBundle(out)
  let bErr = bundle ? nodeCheck(bundle) : 'could not locate app <script> bundle'
  console.log('  [4/' + T + '] ' + pad('App bundle syntax') + (!bErr ? ' PASS' : ' FAIL'))
  if (bErr) errors.push('app bundle: ' + bErr.split('\n')[0])

  const undef = bundle ? undefinedFns(bundle, readSrc('head.html') + '\n' + readSrc('body.html')) : []
  console.log('  [5/' + T + '] ' + pad('Undefined-function scan') + (!undef.length ? ' PASS (0 issues)' : ' FAIL (' + undef.length + ')'))
  undef.forEach(u => errors.push('called but never defined: ' + u + '()'))

  if (!errors.length) { console.log('\n  ✓ All checks passed\n') }
  else { console.error('\n  ✗ Build verification failed:'); errors.forEach(e => console.error('    - ' + e)); console.error(''); process.exit(1) }
}


function writeChecksums() {
  // sha256 of the shipped files, in `sha256  filename` format. Committed to the
  // repo so the in-app updater can verify a download before applying it.
  const files = ['index.html', 'server.txt'].filter(f => fs.existsSync(path.join(ROOT, f)))
  const lines = files.map(f => fileHash(f) + '  ' + f)
  fs.writeFileSync(path.join(ROOT, 'checksums.txt'), lines.join('\n') + '\n')
  console.log('  \u2713 Wrote checksums.txt  [' + files.join(', ') + ']')
}

function build() {
  if (!fs.existsSync(SRC_DIR)) { console.error('✗ src/ not found at', SRC_DIR); process.exit(1) }
  const all = fs.readdirSync(SRC_DIR).sort()
  if (all.indexOf('head.html') === -1) { console.error('✗ src/head.html missing'); process.exit(1) }
  if (all.indexOf('tail.html') === -1) { console.error('✗ src/tail.html missing'); process.exit(1) }
  if (all.indexOf('styles.css') === -1) { console.error('✗ src/styles.css missing'); process.exit(1) }
  if (all.indexOf('body.html') === -1) { console.error('✗ src/body.html missing'); process.exit(1) }
  const jsFiles = all.filter(f => f.endsWith('.js'))
  if (!jsFiles.length) { console.error('✗ no JS modules in src/'); process.exit(1) }

  const css  = readSrc('styles.css')
  const head = readSrc('head.html').replace('/*__LCL_CSS__*/', () => css)
  const parts = [TOP_BANNER, head, readSrc('body.html')]
  for (const f of jsFiles) { parts.push(sectionBanner(f)); parts.push(readSrc(f).trim()); parts.push('\n') }
  parts.push(readSrc('tail.html'))
  const out = parts.join('')
  fs.writeFileSync(OUT_FILE, out, 'utf8')

  console.log('✓ Wrote ' + OUT_FILE)
  console.log('  ' + (out.length / 1024).toFixed(1) + ' KB from ' + (jsFiles.length + 4) + ' source files')
  verify(out, jsFiles)
  writeChecksums()
}

build()
